services:
  database:
    container_name: 'shortener-db'
    image: mysql:8.0.29
    restart: always
    volumes:
      - shortener-db:/var/lib/mysql
    networks:
      - shortener-networks
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  app:
    container_name: 'shortener-app'
    restart: always
    image: shortener:0.1
    # build:
    #   context: .
    networks:
      - shortener-networks
    ports:
      - '3000:3000'
    volumes:
      - .:/src
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  shortener-networks:


volumes:
  shortener-db:
